### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [shemhazai/BatteryDrainer#1]
Greetings, I just made a logo for your project, hope you like it.
![bt1](https://user-images.githubusercontent.com/35619342/39610642-d0b80e06-4f1f-11e8-85b7-865493ff0810.png)
![bt2](https://user-images.githubusercontent.com/35619342/39610644-d4bfd768-4f1f-11e8-9db2-27a240911e3d.png)
If you liked it, let me know which variation and I'll upload the files on a pull request.
Also please tell me if you want me to add/modify something. :DD

**Comment by shemhazai** [comment]
@michaelizer Your icons are great but this is really educational project... I want to do everything by myself, also icons - probably adaptive ones.
